Make rearrange_ranks resilient to race conditions
In less strict isolation levels, the first or last row according to the ranking
may disappear after a rank conflict is identified, but before rearranging
occurs. Allow for approximate ordering in this case.

Serializable isolation level should still guarantee strict ordering.

undefined method `rank' for nil:NilClass

[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model/ranker.rb:177 :in `rearrange_ranks`
[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model/ranker.rb:166 :in `assure_unique_position`
[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model/ranker.rb:61 :in `handle_ranking`
[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model.rb:31 :in `block in handle_ranking`
[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model.rb:30 :in `each`
[GEM_ROOT]/gems/ranked-model-0.4.0/lib/ranked-model.rb:30 :in `handle_ranking`